CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE sales_rep (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL UNIQUE,
    home_base geometry(Point,4326) NOT NULL
);

CREATE TABLE customer (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    address           VARCHAR(500) NOT NULL,
    location          geometry(Point,4326) NOT NULL,
    priority          VARCHAR(20) NOT NULL,
    time_window_open  TIME,
    time_window_close TIME,
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT customer_priority_chk CHECK (priority IN ('LOW', 'NORMAL', 'KEY')),
    CONSTRAINT customer_time_window_both_or_none_chk CHECK ((time_window_open IS NULL) = (time_window_close IS NULL)),
    CONSTRAINT customer_time_window_order_chk CHECK (time_window_open IS NULL OR time_window_open < time_window_close)
);

CREATE TABLE route_plan (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_rep_id           BIGINT NOT NULL REFERENCES sales_rep (id),
    plan_date              DATE NOT NULL,
    total_distance_meters  DOUBLE PRECISION NOT NULL DEFAULT 0,
    naive_distance_meters  DOUBLE PRECISION NOT NULL DEFAULT 0,
    computed_at            TIMESTAMPTZ,
    CONSTRAINT route_plan_total_distance_chk CHECK (total_distance_meters >= 0),
    CONSTRAINT route_plan_naive_distance_chk CHECK (naive_distance_meters >= 0)
);

CREATE TABLE route_stop (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_plan_id    BIGINT NOT NULL REFERENCES route_plan (id) ON DELETE CASCADE,
    customer_id      BIGINT NOT NULL REFERENCES customer (id),
    sequence_index   INT NOT NULL,
    estimated_arrival TIME,
    CONSTRAINT route_stop_sequence_index_chk CHECK (sequence_index >= 0),
    CONSTRAINT route_stop_plan_sequence_uq UNIQUE (route_plan_id, sequence_index)
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL,
    sales_rep_id  BIGINT REFERENCES sales_rep (id),
    CONSTRAINT app_user_role_chk CHECK (role IN ('ADMIN', 'MANAGER', 'REP'))
);

CREATE INDEX customer_location_gix ON customer USING GIST ((location::geography));

CREATE INDEX route_plan_sales_rep_id_plan_date_idx ON route_plan (sales_rep_id, plan_date);
